#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
cd "$SCRIPT_DIR"
COMMAND=$1

if [ -n "$1" ]; then
    shift
fi

case "$COMMAND" in
    send)      bash commands/send.sh "$@" ;;
    ping)      bash commands/ping.sh "$@" ;;
    contacts)  bash commands/contacts.sh "$@" ;;
    log)       bash commands/history.sh "$@" ;;
    *)         echo "Usage: pipevault [send|ping|contacts|log] [options]" ;;
esac
